zip:
	zip -r mapfeel.zip \
		manifest.json \
		background.js \
		content.js \
		jquery.min.js \
		leaflet.css \
		leaflet.js \
		mapfeel_app.js \
		mapfeel_render.js \
		mapfeel.html \
		mapfeel1024.png \
		mapfeel128.png \
		mapfeel48.png \
		mapfeel_icon_128.png \
		mapfeel_icon_48.png

#	zip -r mapfeel.zip mapfeel.zip . \
#	zip -r ../mapfeel.zip . -x ".*" -x "__MACOSX/*" -x ".DS_Store" -x "Makefile"
